In [63]:
import pandas as pd
import numpy as np
import pkg_resources


In [64]:
pip install PyDistances

Note: you may need to restart the kernel to use updated packages.


In [65]:
version = pkg_resources.get_distribution('PyDistances').version
print(version)

0.0.9


In [66]:
import PyDistances

In [67]:
from PyDistances import Euclidean_Dist, Euclidean_Dist_Matrix, Minkowski_Dist, Minkowski_Dist_Matrix, Canberra_Dist, Canberra_Dist_Matrix, Pearson_Dist, Pearson_Dist_Matrix, Mahalanobis_Dist, Mahalanobis_Dist_Matrix, a_b_c_d_Matrix, Sokal_Similarity, Sokal_Dist, Sokal_Dist_Matrix, Jaccard_Similarity, Jaccard_Dist, Jaccard_Dist_Matrix, alpha, Matching_Similarity, Matching_Dist, Matching_Dist_Matrix, Gower_Similarity_Matrix, Gower_Dist_Matrix, Robust_Mahalanobis_Dist, Robust_Mahalanobis_Dist_Matrix, GeneralizedGowerDistance

In [68]:
Data = pd.read_csv('House_Price.csv')

In [69]:
Data = Data.loc[0:150, ['latitude', 'longitude', 'price', 'size_in_m_2', 'balcony_recode', 'private_garden_recode', 'private_gym_recode', 'quality_recode', 'no_of_bathrooms', 'no_of_bedrooms']]

In [70]:
Data_quant = Data.loc[:,['latitude', 'longitude', 'price', 'size_in_m_2']]
Data_binary = Data.loc[:,['balcony_recode', 'private_garden_recode', 'private_gym_recode']]
Data_multiclass = Data.loc[:,['quality_recode', 'no_of_bathrooms', 'no_of_bedrooms']]

In [71]:
Data # p1=4, p2=3, p3=3

latitude  longitude     price  size_in_m_2  balcony_recode  \
0    25.113208  55.138932   2700000   100.242337             1.0   
1    25.106809  55.151201   2850000   146.972546             1.0   
2    25.063302  55.137728   1150000   181.253753             1.0   
3    25.227295  55.341761   2850000   187.664060             1.0   
4    25.114275  55.139764   1729200    47.101821             0.0   
..         ...        ...       ...          ...             ...   
146  25.044572  55.218948    390000    78.874647             1.0   
147  25.089719  55.170481   1650000   135.452574             1.0   
148  25.072791  55.129829   1200000   117.243586             1.0   
149  25.112725  55.109525   5400000   420.478978             1.0   
150  25.073590  55.126352  14800000   466.187254             1.0   

     private_garden_recode  private_gym_recode  quality_recode  \
0                      0.0                 0.0             2.0   
1                      0.0                 0.0             2.0   
2                      0.0                 0.0             2.0   
3                      0.0                 0.0             1.0   
4                      0.0                 0.0             2.0   
..                     ...                 ...             ...   
146                    0.0                 0.0             2.0   
147                    0.0                 0.0             2.0   
148                    0.0                 0.0             2.0   
149                    0.0                 0.0             2.0   
150                    0.0                 1.0             0.0   

     no_of_bathrooms  no_of_bedrooms  
0                  2               1  
1                  2               2  
2                  5               3  
3                  3               2  
4                  1               0  
..               ...             ...  
146                2               1  
147                2               2  
148                2               2  
149                5               4  
150                5               5  

[151 rows x 10 columns]

In [72]:
Euclidean_Dist(Data_quant.iloc[0,:], Data_quant.iloc[0,:])

0.0

In [73]:
Euclidean_Dist(Data_quant.iloc[0,:], Data_quant.iloc[2,:])

1550000.002117049

In [74]:
Euclidean_Dist_Matrix(Data_quant)

array([[       0.        ,   150000.00727904,  1550000.00211705, ...,
         1500000.00009635,  2700000.01899102, 12100000.00553371],
       [  150000.00727904,        0.        ,  1700000.00034565, ...,
         1650000.00026782,  2550000.0146678 , 11950000.00426352],
       [ 1550000.00211705,  1700000.00034565,        0.        , ...,
           50000.040973  ,  4250000.00673279, 13650000.00297389],
       ...,
       [ 1500000.00009635,  1650000.00026782,    50000.040973  , ...,
               0.        ,  4200000.01094663, 13600000.00447653],
       [ 2700000.01899102,  2550000.0146678 ,  4250000.00673279, ...,
         4200000.01094663,        0.        ,  9400000.00011113],
       [12100000.00553371, 11950000.00426352, 13650000.00297389, ...,
        13600000.00447653,  9400000.00011113,        0.        ]])

In [75]:
Minkowski_Dist(Data_quant.iloc[0,:], Data_quant.iloc[0,:], q=1)

0.0

In [76]:
Minkowski_Dist(Data_quant.iloc[0,:], Data_quant.iloc[2,:], q=1)

1550081.062526

In [77]:
Minkowski_Dist_Matrix(Data_quant, q=1)

array([[       0.      ,   150046.748877,  1550081.062526, ...,
         1500017.050769,  2700320.266531, 12100365.997115],
       [  150046.748877,        0.      ,  1700034.338187, ...,
         1650029.78435 ,  2550273.554024, 11950319.272776],
       [ 1550081.062526,  1700034.338187,        0.      , ...,
           50064.027555,  4250239.302851, 13650284.955165],
       ...,
       [ 1500017.050769,  1650029.78435 ,    50064.027555, ...,
               0.      ,  4200303.29563 , 13600348.947944],
       [ 2700320.266531,  2550273.554024,  4250239.302851, ...,
         4200303.29563 ,        0.      ,  9400045.764238],
       [12100365.997115, 11950319.272776, 13650284.955165, ...,
        13600348.947944,  9400045.764238,        0.      ]])

In [78]:
Canberra_Dist(Data_quant.iloc[0,:], Data_quant.iloc[0,:])

0.0

In [79]:
Canberra_Dist(Data_quant.iloc[0,:], Data_quant.iloc[2,:])

0.6913917083019879

In [80]:
Canberra_Dist_Matrix(Data_quant)

array([[0.        , 0.21629237, 0.69139171, ..., 0.463675  , 0.9485963 ,
        1.33838751],
       [0.21629237, 0.        , 0.53043317, ..., 0.52079671, 0.79157752,
        1.19854721],
       [0.69139171, 0.53043317, 0.        , ..., 0.23597883, 1.04765637,
        1.29619958],
       ...,
       [0.463675  , 0.52079671, 0.23597883, ..., 0.        , 1.20126891,
        1.44813664],
       [0.9485963 , 0.79157752, 1.04765637, ..., 1.20126891, 0.        ,
        0.51782969],
       [1.33838751, 1.19854721, 1.29619958, ..., 1.44813664, 0.51782969,
        0.        ]])

In [81]:
Pearson_Dist(Data_quant.iloc[0,:], Data_quant.iloc[0,:], variance=Data.var())

0.0

In [82]:
Pearson_Dist(Data_quant.iloc[0,:], Data_quant.iloc[2,:], variance=Data.var())

1.5393297661160206

In [83]:
Pearson_Dist_Matrix(Data_quant)

array([[0.        , 0.63961801, 1.53932977, ..., 1.03084131, 4.32943281,
        7.47171915],
       [0.63961801, 0.        , 1.20505141, ..., 1.09780711, 3.76643257,
        7.04893716],
       [1.53932977, 1.20505141, 0.        , ..., 0.84617436, 3.79891055,
        7.4670243 ],
       ...,
       [1.03084131, 1.09780711, 0.84617436, ..., 0.        , 4.44143053,
        7.87905955],
       [4.32943281, 3.76643257, 3.79891055, ..., 4.44143053, 0.        ,
        4.57460318],
       [7.47171915, 7.04893716, 7.4670243 , ..., 7.87905955, 4.57460318,
        0.        ]])

In [84]:
Mahalanobis_Dist(Data_quant.iloc[0,:], Data_quant.iloc[2,:], S_inv=np.linalg.inv( np.cov(Data_quant , rowvar=False) ))

2.7671855371187757

In [85]:
Mahalanobis_Dist_Matrix(Data_quant)

array([[0.        , 0.92801614, 2.76718554, ..., 1.52541554, 5.21105193,
        6.45997793],
       [0.92801614, 0.        , 1.96135599, ..., 0.98693199, 4.43479282,
        6.2920865 ],
       [2.76718554, 1.96135599, 0.        , ..., 1.3592188 , 3.4307313 ,
        7.27986558],
       ...,
       [1.52541554, 0.98693199, 1.3592188 , ..., 0.        , 4.41360406,
        7.01503103],
       [5.21105193, 4.43479282, 3.4307313 , ..., 4.41360406, 0.        ,
        7.4691448 ],
       [6.45997793, 6.2920865 , 7.27986558, ..., 7.01503103, 7.4691448 ,
        0.        ]])

In [86]:
a,b,c,d,p = a_b_c_d_Matrix(Data_binary)

In [87]:
Sokal_Similarity(i=0, r=2, a=a, d=d, p=p)

1.0

In [88]:
Sokal_Dist(i=0, r=2, a=a, d=d, p=p)

0.0

In [89]:
Sokal_Dist_Matrix(Data_binary)

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.81649658],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.81649658],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.81649658],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.81649658],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.81649658],
       [0.81649658, 0.81649658, 0.81649658, ..., 0.81649658, 0.81649658,
        0.        ]])

In [98]:
Jaccard_Similarity(i=0, r=0, a=a, d=d, p=p)

1.0

In [102]:
Jaccard_Similarity(i=0, r=2, a=a, d=d, p=p)

1.0

In [96]:
Jaccard_Dist(i=0, r=2, a=a, d=d, p=p)

0.0

In [101]:
Jaccard_Dist_Matrix(Data_binary)

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [104]:
Matching_Similarity(x_i=Data_multiclass.iloc[0,:], x_r=Data_multiclass.iloc[2,:], Data=Data_multiclass)

0.3333333333333333

In [105]:
Matching_Dist(x_i=Data_multiclass.iloc[0,:], x_r=Data_multiclass.iloc[2,:], Data=Data_multiclass)

1.1547005383792517

In [106]:
Matching_Dist_Matrix(Data_multiclass)

array([[0.        , 0.81649658, 1.15470054, ..., 0.81649658, 1.15470054,
        1.41421356],
       [0.81649658, 0.        , 1.15470054, ..., 0.        , 1.15470054,
        1.41421356],
       [1.15470054, 1.15470054, 0.        , ..., 1.15470054, 0.81649658,
        1.15470054],
       ...,
       [0.81649658, 0.        , 1.15470054, ..., 0.        , 1.15470054,
        1.41421356],
       [1.15470054, 1.15470054, 0.81649658, ..., 1.15470054, 0.        ,
        1.15470054],
       [1.41421356, 1.41421356, 1.15470054, ..., 1.41421356, 1.15470054,
        0.        ]])

In [108]:
Gower_Similarity_Matrix(Data, p1=4, p2=3, p3=3)

array([[1.        , 0.85175283, 0.68485131, ..., 0.83008431, 0.62482353,
        0.34709882],
       [0.85175283, 1.        , 0.69489168, ..., 0.94863663, 0.63064768,
        0.35833279],
       [0.68485131, 0.69489168, 1.        , ..., 0.72293677, 0.73120218,
        0.48172501],
       ...,
       [0.83008431, 0.94863663, 0.72293677, ..., 1.        , 0.59776459,
        0.36311382],
       [0.62482353, 0.63064768, 0.73120218, ..., 0.59776459, 1.        ,
        0.55654437],
       [0.34709882, 0.35833279, 0.48172501, ..., 0.36311382, 0.55654437,
        1.        ]])

In [110]:
Gower_Dist_Matrix(Data, p1=4, p2=3, p3=3)

array([[0.        , 0.38502879, 0.56138105, ..., 0.41220831, 0.61251651,
        0.808023  ],
       [0.38502879, 0.        , 0.55236611, ..., 0.22663488, 0.60774363,
        0.80104133],
       [0.56138105, 0.55236611, 0.        , ..., 0.52636796, 0.51845716,
        0.71991318],
       ...,
       [0.41220831, 0.22663488, 0.52636796, ..., 0.        , 0.63422032,
        0.79805149],
       [0.61251651, 0.60774363, 0.51845716, ..., 0.63422032, 0.        ,
        0.66592464],
       [0.808023  , 0.80104133, 0.71991318, ..., 0.79805149, 0.66592464,
        0.        ]])

In [111]:
Robust_Mahalanobis_Dist(x_i=Data_quant.iloc[0,:], x_r=Data_quant.iloc[2,:], Data=Data_quant, Method='MAD', epsilon=0.05, n_iters=20)

2.1448247626892223

In [113]:
Robust_Mahalanobis_Dist(x_i=Data_quant.iloc[0,:], x_r=Data_quant.iloc[2,:], Data=Data_quant, Method='trimmed', alpha=0.1, epsilon=0.05, n_iters=20)

2.7434709885399884

In [114]:
Robust_Mahalanobis_Dist(x_i=Data_quant.iloc[0,:], x_r=Data_quant.iloc[2,:], Data=Data_quant, Method='winsorized', alpha=0.1, epsilon=0.05, n_iters=20)

2.8446274140577943

In [117]:
Robust_Mahalanobis_Dist_Matrix(Data=Data_quant, Method='trimmed', alpha=0.1, epsilon=0.05, n_iters=20)

TypeError: Mahalanobis_Dist() got an unexpected keyword argument 'x'