In [1]:
import pandas as pd
import numpy as np
import pkg_resources


In [ ]:
pip install PyDistances

In [ ]:
version = pkg_resources.get_distribution('PyDistances').version
print(version)

In [ ]:
import PyDistances

In [ ]:
from PyDistances import Euclidean_Dist, Euclidean_Dist_Matrix, Minkowski_Dist, Minkowski_Dist_Matrix, Canberra_Dist, Canberra_Dist_Matrix, Pearson_Dist,  Pearson_Dist_Matrix, Mahalanobis_Dist, Mahalanobis_Dist_Matrix, a_b_c_d_Matrix, Sokal_Similarity, Sokal_Dist, Sokal_Dist_Matrix, Jaccard_Similarity, Jaccard_Dist, Jaccard_Dist_Matrix, alpha, Matching_Similarity, Matching_Dist, Matching_Dist_Matrix, Gower_Similarity_Matrix, Gower_Dist_Matrix, Robust_Mahalanobis_Dist, Robust_Mahalanobis_Dist_Matrix, GeneralizedGowerDistance

In [2]:
Data = pd.read_csv('House_Price.csv')

In [3]:
Data = Data.loc[0:150, ['latitude', 'longitude', 'price', 'size_in_m_2', 'balcony_recode', 'private_garden_recode', 'private_gym_recode', 'quality_recode', 'no_of_bathrooms', 'no_of_bedrooms']]

In [4]:
Data # p1=4, p2=3, p3=3

latitude  longitude     price  size_in_m_2  balcony_recode  \
0    25.113208  55.138932   2700000   100.242337             1.0   
1    25.106809  55.151201   2850000   146.972546             1.0   
2    25.063302  55.137728   1150000   181.253753             1.0   
3    25.227295  55.341761   2850000   187.664060             1.0   
4    25.114275  55.139764   1729200    47.101821             0.0   
..         ...        ...       ...          ...             ...   
146  25.044572  55.218948    390000    78.874647             1.0   
147  25.089719  55.170481   1650000   135.452574             1.0   
148  25.072791  55.129829   1200000   117.243586             1.0   
149  25.112725  55.109525   5400000   420.478978             1.0   
150  25.073590  55.126352  14800000   466.187254             1.0   

     private_garden_recode  private_gym_recode  quality_recode  \
0                      0.0                 0.0             2.0   
1                      0.0                 0.0             2.0   
2                      0.0                 0.0             2.0   
3                      0.0                 0.0             1.0   
4                      0.0                 0.0             2.0   
..                     ...                 ...             ...   
146                    0.0                 0.0             2.0   
147                    0.0                 0.0             2.0   
148                    0.0                 0.0             2.0   
149                    0.0                 0.0             2.0   
150                    0.0                 1.0             0.0   

     no_of_bathrooms  no_of_bedrooms  
0                  2               1  
1                  2               2  
2                  5               3  
3                  3               2  
4                  1               0  
..               ...             ...  
146                2               1  
147                2               2  
148                2               2  
149                5               4  
150                5               5  

[151 rows x 10 columns]

In [9]:
Euclidean_Dist(Data.iloc[0,:], Data.iloc[0,:])

0.0

In [10]:
Euclidean_Dist(Data.iloc[0,:], Data.iloc[2,:])

1550000.0021212427

In [11]:
Euclidean_Dist_Matrix(Data)

array([[       0.        ,   150000.00728238,  1550000.00212124, ...,
         1500000.00009668,  2700000.01899435, 12100000.00553495],
       [  150000.00728238,        0.        ,  1700000.00034859, ...,
         1650000.00026782,  2550000.01467035, 11950000.00426448],
       [ 1550000.00212124,  1700000.00034859,        0.        , ...,
           50000.041073  ,  4250000.00673291, 13650000.00297422],
       ...,
       [ 1500000.00009668,  1650000.00026782,    50000.041073  , ...,
               0.        ,  4200000.01094818, 13600000.00447738],
       [ 2700000.01899435,  2550000.01467035,  4250000.00673291, ...,
         4200000.01094818,        0.        ,  9400000.00011145],
       [12100000.00553495, 11950000.00426448, 13650000.00297422, ...,
        13600000.00447738,  9400000.00011145,        0.        ]])

In [12]:
Minkowski_Dist(Data.iloc[0,:], Data.iloc[0,:], q=1)

0.0

In [13]:
Minkowski_Dist(Data.iloc[0,:], Data.iloc[2,:], q=1)

1550086.062526

In [14]:
Minkowski_Dist_Matrix(Data, q=1)

array([[       0.      ,   150047.748877,  1550086.062526, ...,
         1500018.050769,  2700326.266531, 12100375.997115],
       [  150047.748877,        0.      ,  1700038.338187, ...,
         1650029.78435 ,  2550278.554024, 11950328.272776],
       [ 1550086.062526,  1700038.338187,        0.      , ...,
           50068.027555,  4250240.302851, 13650289.955165],
       ...,
       [ 1500018.050769,  1650029.78435 ,    50068.027555, ...,
               0.      ,  4200308.29563 , 13600357.947944],
       [ 2700326.266531,  2550278.554024,  4250240.302851, ...,
         4200308.29563 ,        0.      ,  9400049.764238],
       [12100375.997115, 11950328.272776, 13650289.955165, ...,
        13600357.947944,  9400049.764238,        0.      ]])

In [15]:
Canberra_Dist(Data.iloc[0,:], Data.iloc[0,:])

0.0

In [16]:
Canberra_Dist(Data.iloc[0,:], Data.iloc[2,:])

1.6199631368734164

In [17]:
Canberra_Dist_Matrix(Data)

array([[0.        , 0.5496257 , 1.61996314, ..., 0.79700834, 1.97716773,
        4.4336256 ],
       [0.5496257 , 0.        , 1.15900459, ..., 0.52079671, 1.55348228,
        4.05569007],
       [1.61996314, 1.15900459, 0.        , ..., 0.86455026, 1.19051351,
        3.54619958],
       ...,
       [0.79700834, 0.52079671, 0.86455026, ..., 0.        , 1.96317367,
        4.3052795 ],
       [1.97716773, 1.55348228, 1.19051351, ..., 1.96317367, 0.        ,
        2.6289408 ],
       [4.4336256 , 4.05569007, 3.54619958, ..., 4.3052795 , 2.6289408 ,
        0.        ]])

In [18]:
Pearson_Dist(Data.iloc[0,:], Data.iloc[0,:], variance=Data.var())

0.0

In [19]:
Pearson_Dist(Data.iloc[0,:], Data.iloc[2,:], variance=Data.var())

3.8222980656608074

In [20]:
Pearson_Dist_Matrix(Data)

array([[ 0.        ,  1.26658427,  3.82229807, ...,  1.50258389,
         6.07947674, 11.99245944],
       [ 1.26658427,  0.        ,  3.17918255, ...,  1.09780711,
         5.1406654 , 11.37163751],
       [ 3.82229807,  3.17918255,  0.        , ...,  3.06121934,
         3.95308055, 11.04298536],
       ...,
       [ 1.50258389,  1.09780711,  3.06121934, ...,  0.        ,
         5.65391294, 11.9040415 ],
       [ 6.07947674,  5.1406654 ,  3.95308055, ...,  5.65391294,
         0.        ,  9.13962223],
       [11.99245944, 11.37163751, 11.04298536, ..., 11.9040415 ,
         9.13962223,  0.        ]])

In [23]:
Mahalanobis_Dist(Data.iloc[0,:], Data.iloc[2,:], S_inv=np.linalg.inv( np.cov(Data , rowvar=False) ))

4.017378957083443

In [24]:
Mahalanobis_Dist_Matrix(Data)

array([[ 0.        ,  2.20973946,  4.01737896, ...,  2.67826799,
         5.23251681,  9.42307625],
       [ 2.20973946,  0.        ,  4.31689005, ...,  1.19767771,
         4.86703402,  9.22661383],
       [ 4.01737896,  4.31689005,  0.        , ...,  3.77523411,
         4.67787355, 10.27884472],
       ...,
       [ 2.67826799,  1.19767771,  3.77523411, ...,  0.        ,
         4.94907521,  9.54834209],
       [ 5.23251681,  4.86703402,  4.67787355, ...,  4.94907521,
         0.        , 10.19635899],
       [ 9.42307625,  9.22661383, 10.27884472, ...,  9.54834209,
        10.19635899,  0.        ]])